# yaml-language-server: $schema=https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Architectures:
      - x86_64
    Timeout: 200
    Handler: bootstrap
    Runtime: provided.al2023

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaDynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: arn:aws:dynamodb:ap-south-1:513758042129:table/pm_nosql

  EmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  Login:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/auth/login
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /auth/login
            RestApiId: !Ref Api

  Signup:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/auth/signup
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /auth/register
            RestApiId: !Ref Api

  GetBuildings:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/building/get_buildings
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /buildings
            RestApiId: !Ref Api

  AddBuilding:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/building/add_building
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /buildings
            RestApiId: !Ref Api

  DeleteBuilding:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/building/delete_building
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /buildings/{buildingId}
            RestApiId: !Ref Api

  GetFloors:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/floor/get_floors
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /buildings/{buildingId}/floors
            RestApiId: !Ref Api

  AddFloor:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/floor/add_floor
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /buildings/{buildingId}/floors
            RestApiId: !Ref Api

  DeleteFloor:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/floor/delete_floor
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /buildings/{buildingId}/floors/{floorId}
            RestApiId: !Ref Api

  GetBuildingOffices:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/office/get_offices
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /buildings/{buildingId}/offices
            RestApiId: !Ref Api

  GetAllOffices:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/office/get_all_offices
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /offices
            RestApiId: !Ref Api

  AddOffice:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/office/add_office
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /buildings/{buildingId}/offices
            RestApiId: !Ref Api

  DeleteOffice:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/office/delete_office
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /buildings/{buildingId}/offices/{officeId}
            RestApiId: !Ref Api

  GetSlots:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/slot/get_slots
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /buildings/{buildingId}/floors/{floorId}/slots
            RestApiId: !Ref Api

  GetUsers:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/user/get_users
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /users
            RestApiId: !Ref Api

  UpdateUser:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/user/update_user
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /users/{userId}
            RestApiId: !Ref Api

  DeleteUser:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/user/delete_user
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /users/{userId}
            RestApiId: !Ref Api

  GetVehicles:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/vehicle/get_vehicles
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /vehicles
            RestApiId: !Ref Api

  RegisterVehicle:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/vehicle/register_vehicle
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /vehicles
            RestApiId: !Ref Api

  RemoveVehicle:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/vehicle/remove_vehicle
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /vehicles/{numberplate}
            RestApiId: !Ref Api

  AddParking:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/parking/add_parking
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /parkings
            RestApiId: !Ref Api

  GetParkings:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/parking/get_parkings
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /parkings
            RestApiId: !Ref Api

  UnparkVehicle:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/functions/parking/unpark_vehicle
      Role: !GetAtt LambdaRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /parkings/{numberplate}/unpark
            RestApiId: !Ref Api

  GetMonthlyBill:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/functions/billing/get_monthly_bill
      Handler: main
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetMonthlyBill:
          Type: Api
          Properties:
            Path: /billing
            Method: get
            RestApiId: !Ref Api

  GenerateBill:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/functions/billing/generate_bill
      Handler: main
      Role: !GetAtt LambdaRole.Arn
      Events:
        MonthlySchedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(30 days)

  SendEmail:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/functions/billing/email
      Handler: main
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EmailQueue.Arn
