// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/auth_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	roles "github.com/Kaushik1766/ParkingManagement/internal/models/enums/roles"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticationManager is a mock of AuthenticationManager interface.
type MockAuthenticationManager struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationManagerMockRecorder
	isgomock struct{}
}

// MockAuthenticationManagerMockRecorder is the mock recorder for MockAuthenticationManager.
type MockAuthenticationManagerMockRecorder struct {
	mock *MockAuthenticationManager
}

// NewMockAuthenticationManager creates a new mock instance.
func NewMockAuthenticationManager(ctrl *gomock.Controller) *MockAuthenticationManager {
	mock := &MockAuthenticationManager{ctrl: ctrl}
	mock.recorder = &MockAuthenticationManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationManager) EXPECT() *MockAuthenticationManagerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthenticationManager) Login(ctx context.Context, loginReq models.LoginRequestDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, loginReq)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthenticationManagerMockRecorder) Login(ctx, loginReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthenticationManager)(nil).Login), ctx, loginReq)
}

// Signup mocks base method.
func (m *MockAuthenticationManager) Signup(ctx context.Context, registerReq models.RegisterRequestDTO, role roles.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, registerReq, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signup indicates an expected call of Signup.
func (mr *MockAuthenticationManagerMockRecorder) Signup(ctx, registerReq, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockAuthenticationManager)(nil).Signup), ctx, registerReq, role)
}
