// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/billing_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBillingMgr is a mock of BillingMgr interface.
type MockBillingMgr struct {
	ctrl     *gomock.Controller
	recorder *MockBillingMgrMockRecorder
	isgomock struct{}
}

// MockBillingMgrMockRecorder is the mock recorder for MockBillingMgr.
type MockBillingMgrMockRecorder struct {
	mock *MockBillingMgr
}

// NewMockBillingMgr creates a new mock instance.
func NewMockBillingMgr(ctrl *gomock.Controller) *MockBillingMgr {
	mock := &MockBillingMgr{ctrl: ctrl}
	mock.recorder = &MockBillingMgrMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingMgr) EXPECT() *MockBillingMgrMockRecorder {
	return m.recorder
}

// GenerateMonthlyInvoice mocks base method.
func (m *MockBillingMgr) GenerateMonthlyInvoice() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateMonthlyInvoice")
}

// GenerateMonthlyInvoice indicates an expected call of GenerateMonthlyInvoice.
func (mr *MockBillingMgrMockRecorder) GenerateMonthlyInvoice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMonthlyInvoice", reflect.TypeOf((*MockBillingMgr)(nil).GenerateMonthlyInvoice))
}
