// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/building_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildingStorage is a mock of BuildingStorage interface.
type MockBuildingStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBuildingStorageMockRecorder
	isgomock struct{}
}

// MockBuildingStorageMockRecorder is the mock recorder for MockBuildingStorage.
type MockBuildingStorageMockRecorder struct {
	mock *MockBuildingStorage
}

// NewMockBuildingStorage creates a new mock instance.
func NewMockBuildingStorage(ctrl *gomock.Controller) *MockBuildingStorage {
	mock := &MockBuildingStorage{ctrl: ctrl}
	mock.recorder = &MockBuildingStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildingStorage) EXPECT() *MockBuildingStorageMockRecorder {
	return m.recorder
}

// AddBuilding mocks base method.
func (m *MockBuildingStorage) AddBuilding(buildingName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBuilding", buildingName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBuilding indicates an expected call of AddBuilding.
func (mr *MockBuildingStorageMockRecorder) AddBuilding(buildingName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBuilding", reflect.TypeOf((*MockBuildingStorage)(nil).AddBuilding), buildingName)
}

// DeleteBuildingByID mocks base method.
func (m *MockBuildingStorage) DeleteBuildingByID(buildingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBuildingByID", buildingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBuildingByID indicates an expected call of DeleteBuildingByID.
func (mr *MockBuildingStorageMockRecorder) DeleteBuildingByID(buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBuildingByID", reflect.TypeOf((*MockBuildingStorage)(nil).DeleteBuildingByID), buildingID)
}

// DeleteBuildingByName mocks base method.
func (m *MockBuildingStorage) DeleteBuildingByName(buildingName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBuildingByName", buildingName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBuildingByName indicates an expected call of DeleteBuildingByName.
func (mr *MockBuildingStorageMockRecorder) DeleteBuildingByName(buildingName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBuildingByName", reflect.TypeOf((*MockBuildingStorage)(nil).DeleteBuildingByName), buildingName)
}

// GetAllBuildings mocks base method.
func (m *MockBuildingStorage) GetAllBuildings() ([]models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBuildings")
	ret0, _ := ret[0].([]models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBuildings indicates an expected call of GetAllBuildings.
func (mr *MockBuildingStorageMockRecorder) GetAllBuildings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBuildings", reflect.TypeOf((*MockBuildingStorage)(nil).GetAllBuildings))
}

// GetBuildingByID mocks base method.
func (m *MockBuildingStorage) GetBuildingByID(buildingID uuid.UUID) (models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingByID", buildingID)
	ret0, _ := ret[0].(models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingByID indicates an expected call of GetBuildingByID.
func (mr *MockBuildingStorageMockRecorder) GetBuildingByID(buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingByID", reflect.TypeOf((*MockBuildingStorage)(nil).GetBuildingByID), buildingID)
}

// GetBuildingByName mocks base method.
func (m *MockBuildingStorage) GetBuildingByName(buildingName string) (models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingByName", buildingName)
	ret0, _ := ret[0].(models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingByName indicates an expected call of GetBuildingByName.
func (mr *MockBuildingStorageMockRecorder) GetBuildingByName(buildingName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingByName", reflect.TypeOf((*MockBuildingStorage)(nil).GetBuildingByName), buildingName)
}
