// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/building_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildingStorage is a mock of BuildingStorage interface.
type MockBuildingStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBuildingStorageMockRecorder
	isgomock struct{}
}

// MockBuildingStorageMockRecorder is the mock recorder for MockBuildingStorage.
type MockBuildingStorageMockRecorder struct {
	mock *MockBuildingStorage
}

// NewMockBuildingStorage creates a new mock instance.
func NewMockBuildingStorage(ctrl *gomock.Controller) *MockBuildingStorage {
	mock := &MockBuildingStorage{ctrl: ctrl}
	mock.recorder = &MockBuildingStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildingStorage) EXPECT() *MockBuildingStorageMockRecorder {
	return m.recorder
}

// AddBuilding mocks base method.
func (m *MockBuildingStorage) AddBuilding(ctx context.Context, buildingName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBuilding", ctx, buildingName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBuilding indicates an expected call of AddBuilding.
func (mr *MockBuildingStorageMockRecorder) AddBuilding(ctx, buildingName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBuilding", reflect.TypeOf((*MockBuildingStorage)(nil).AddBuilding), ctx, buildingName)
}

// DeleteBuildingByID mocks base method.
func (m *MockBuildingStorage) DeleteBuildingByID(ctx context.Context, buildingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBuildingByID", ctx, buildingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBuildingByID indicates an expected call of DeleteBuildingByID.
func (mr *MockBuildingStorageMockRecorder) DeleteBuildingByID(ctx, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBuildingByID", reflect.TypeOf((*MockBuildingStorage)(nil).DeleteBuildingByID), ctx, buildingID)
}

// GetAllBuildingSummary mocks base method.
func (m *MockBuildingStorage) GetAllBuildingSummary(ctx context.Context) ([]models.BuildingSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBuildingSummary", ctx)
	ret0, _ := ret[0].([]models.BuildingSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBuildingSummary indicates an expected call of GetAllBuildingSummary.
func (mr *MockBuildingStorageMockRecorder) GetAllBuildingSummary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBuildingSummary", reflect.TypeOf((*MockBuildingStorage)(nil).GetAllBuildingSummary), ctx)
}

// GetAllBuildings mocks base method.
func (m *MockBuildingStorage) GetAllBuildings(ctx context.Context) ([]models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBuildings", ctx)
	ret0, _ := ret[0].([]models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBuildings indicates an expected call of GetAllBuildings.
func (mr *MockBuildingStorageMockRecorder) GetAllBuildings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBuildings", reflect.TypeOf((*MockBuildingStorage)(nil).GetAllBuildings), ctx)
}

// GetBuildingByID mocks base method.
func (m *MockBuildingStorage) GetBuildingByID(ctx context.Context, buildingID uuid.UUID) (models.Building, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingByID", ctx, buildingID)
	ret0, _ := ret[0].(models.Building)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingByID indicates an expected call of GetBuildingByID.
func (mr *MockBuildingStorageMockRecorder) GetBuildingByID(ctx, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingByID", reflect.TypeOf((*MockBuildingStorage)(nil).GetBuildingByID), ctx, buildingID)
}
