// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/building_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildingMgr is a mock of BuildingMgr interface.
type MockBuildingMgr struct {
	ctrl     *gomock.Controller
	recorder *MockBuildingMgrMockRecorder
	isgomock struct{}
}

// MockBuildingMgrMockRecorder is the mock recorder for MockBuildingMgr.
type MockBuildingMgrMockRecorder struct {
	mock *MockBuildingMgr
}

// NewMockBuildingMgr creates a new mock instance.
func NewMockBuildingMgr(ctrl *gomock.Controller) *MockBuildingMgr {
	mock := &MockBuildingMgr{ctrl: ctrl}
	mock.recorder = &MockBuildingMgrMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildingMgr) EXPECT() *MockBuildingMgrMockRecorder {
	return m.recorder
}

// AddBuilding mocks base method.
func (m *MockBuildingMgr) AddBuilding(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBuilding", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBuilding indicates an expected call of AddBuilding.
func (mr *MockBuildingMgrMockRecorder) AddBuilding(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBuilding", reflect.TypeOf((*MockBuildingMgr)(nil).AddBuilding), ctx, name)
}

// DeleteBuildingByID mocks base method.
func (m *MockBuildingMgr) DeleteBuildingByID(ctx context.Context, buildingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBuildingByID", ctx, buildingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBuildingByID indicates an expected call of DeleteBuildingByID.
func (mr *MockBuildingMgrMockRecorder) DeleteBuildingByID(ctx, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBuildingByID", reflect.TypeOf((*MockBuildingMgr)(nil).DeleteBuildingByID), ctx, buildingID)
}

// GetAllBuildings mocks base method.
func (m *MockBuildingMgr) GetAllBuildings(ctx context.Context) ([]models.BuildingDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBuildings", ctx)
	ret0, _ := ret[0].([]models.BuildingDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBuildings indicates an expected call of GetAllBuildings.
func (mr *MockBuildingMgrMockRecorder) GetAllBuildings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBuildings", reflect.TypeOf((*MockBuildingMgr)(nil).GetAllBuildings), ctx)
}

// GetBuildingByID mocks base method.
func (m *MockBuildingMgr) GetBuildingByID(ctx context.Context, buildingID string) (models.BuildingDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingByID", ctx, buildingID)
	ret0, _ := ret[0].(models.BuildingDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildingByID indicates an expected call of GetBuildingByID.
func (mr *MockBuildingMgrMockRecorder) GetBuildingByID(ctx, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingByID", reflect.TypeOf((*MockBuildingMgr)(nil).GetBuildingByID), ctx, buildingID)
}
