// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/floor_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFloorStorage is a mock of FloorStorage interface.
type MockFloorStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFloorStorageMockRecorder
	isgomock struct{}
}

// MockFloorStorageMockRecorder is the mock recorder for MockFloorStorage.
type MockFloorStorageMockRecorder struct {
	mock *MockFloorStorage
}

// NewMockFloorStorage creates a new mock instance.
func NewMockFloorStorage(ctrl *gomock.Controller) *MockFloorStorage {
	mock := &MockFloorStorage{ctrl: ctrl}
	mock.recorder = &MockFloorStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFloorStorage) EXPECT() *MockFloorStorageMockRecorder {
	return m.recorder
}

// AddFloor mocks base method.
func (m *MockFloorStorage) AddFloor(buildingId string, floorNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFloor", buildingId, floorNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFloor indicates an expected call of AddFloor.
func (mr *MockFloorStorageMockRecorder) AddFloor(buildingId, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFloor", reflect.TypeOf((*MockFloorStorage)(nil).AddFloor), buildingId, floorNumber)
}

// DeleteFloor mocks base method.
func (m *MockFloorStorage) DeleteFloor(buildingId string, floorNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFloor", buildingId, floorNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFloor indicates an expected call of DeleteFloor.
func (mr *MockFloorStorageMockRecorder) DeleteFloor(buildingId, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFloor", reflect.TypeOf((*MockFloorStorage)(nil).DeleteFloor), buildingId, floorNumber)
}

// GetFloor mocks base method.
func (m *MockFloorStorage) GetFloor(buildingId uuid.UUID, floorNumber int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloor", buildingId, floorNumber)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloor indicates an expected call of GetFloor.
func (mr *MockFloorStorageMockRecorder) GetFloor(buildingId, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloor", reflect.TypeOf((*MockFloorStorage)(nil).GetFloor), buildingId, floorNumber)
}

// GetFloorsByBuildingId mocks base method.
func (m *MockFloorStorage) GetFloorsByBuildingId(buildingId string) ([]models.Floor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloorsByBuildingId", buildingId)
	ret0, _ := ret[0].([]models.Floor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloorsByBuildingId indicates an expected call of GetFloorsByBuildingId.
func (mr *MockFloorStorageMockRecorder) GetFloorsByBuildingId(buildingId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloorsByBuildingId", reflect.TypeOf((*MockFloorStorage)(nil).GetFloorsByBuildingId), buildingId)
}
