// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/office_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOfficeStorage is a mock of OfficeStorage interface.
type MockOfficeStorage struct {
	ctrl     *gomock.Controller
	recorder *MockOfficeStorageMockRecorder
	isgomock struct{}
}

// MockOfficeStorageMockRecorder is the mock recorder for MockOfficeStorage.
type MockOfficeStorageMockRecorder struct {
	mock *MockOfficeStorage
}

// NewMockOfficeStorage creates a new mock instance.
func NewMockOfficeStorage(ctrl *gomock.Controller) *MockOfficeStorage {
	mock := &MockOfficeStorage{ctrl: ctrl}
	mock.recorder = &MockOfficeStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfficeStorage) EXPECT() *MockOfficeStorageMockRecorder {
	return m.recorder
}

// AddOffice mocks base method.
func (m *MockOfficeStorage) AddOffice(ctx context.Context, officeName, buildingID string, floorNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOffice", ctx, officeName, buildingID, floorNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOffice indicates an expected call of AddOffice.
func (mr *MockOfficeStorageMockRecorder) AddOffice(ctx, officeName, buildingID, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOffice", reflect.TypeOf((*MockOfficeStorage)(nil).AddOffice), ctx, officeName, buildingID, floorNumber)
}

// DeleteOffice mocks base method.
func (m *MockOfficeStorage) DeleteOffice(ctx context.Context, officeId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOffice", ctx, officeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOffice indicates an expected call of DeleteOffice.
func (mr *MockOfficeStorageMockRecorder) DeleteOffice(ctx, officeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOffice", reflect.TypeOf((*MockOfficeStorage)(nil).DeleteOffice), ctx, officeId)
}

// GetAllOffices mocks base method.
func (m *MockOfficeStorage) GetAllOffices(ctx context.Context) ([]models.Office, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOffices", ctx)
	ret0, _ := ret[0].([]models.Office)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOffices indicates an expected call of GetAllOffices.
func (mr *MockOfficeStorageMockRecorder) GetAllOffices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOffices", reflect.TypeOf((*MockOfficeStorage)(nil).GetAllOffices), ctx)
}

// GetBuildingAndFloorByOffice mocks base method.
func (m *MockOfficeStorage) GetBuildingAndFloorByOffice(ctx context.Context, officeName string) (uuid.UUID, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildingAndFloorByOffice", ctx, officeName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBuildingAndFloorByOffice indicates an expected call of GetBuildingAndFloorByOffice.
func (mr *MockOfficeStorageMockRecorder) GetBuildingAndFloorByOffice(ctx, officeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildingAndFloorByOffice", reflect.TypeOf((*MockOfficeStorage)(nil).GetBuildingAndFloorByOffice), ctx, officeName)
}

// GetOfficeByName mocks base method.
func (m *MockOfficeStorage) GetOfficeByName(ctx context.Context, officeName string) (models.Office, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOfficeByName", ctx, officeName)
	ret0, _ := ret[0].(models.Office)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOfficeByName indicates an expected call of GetOfficeByName.
func (mr *MockOfficeStorageMockRecorder) GetOfficeByName(ctx, officeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOfficeByName", reflect.TypeOf((*MockOfficeStorage)(nil).GetOfficeByName), ctx, officeName)
}

// GetOfficesByBuilding mocks base method.
func (m *MockOfficeStorage) GetOfficesByBuilding(ctx context.Context, buildingID string) ([]models.Office, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOfficesByBuilding", ctx, buildingID)
	ret0, _ := ret[0].([]models.Office)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOfficesByBuilding indicates an expected call of GetOfficesByBuilding.
func (mr *MockOfficeStorageMockRecorder) GetOfficesByBuilding(ctx, buildingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOfficesByBuilding", reflect.TypeOf((*MockOfficeStorage)(nil).GetOfficesByBuilding), ctx, buildingID)
}
