// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/parking_history_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockParkingHistoryMgr is a mock of ParkingHistoryMgr interface.
type MockParkingHistoryMgr struct {
	ctrl     *gomock.Controller
	recorder *MockParkingHistoryMgrMockRecorder
	isgomock struct{}
}

// MockParkingHistoryMgrMockRecorder is the mock recorder for MockParkingHistoryMgr.
type MockParkingHistoryMgrMockRecorder struct {
	mock *MockParkingHistoryMgr
}

// NewMockParkingHistoryMgr creates a new mock instance.
func NewMockParkingHistoryMgr(ctrl *gomock.Controller) *MockParkingHistoryMgr {
	mock := &MockParkingHistoryMgr{ctrl: ctrl}
	mock.recorder = &MockParkingHistoryMgrMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingHistoryMgr) EXPECT() *MockParkingHistoryMgrMockRecorder {
	return m.recorder
}

// GetActiveUserParkings mocks base method.
func (m *MockParkingHistoryMgr) GetActiveUserParkings(ctx context.Context) ([]models.ParkingHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUserParkings", ctx)
	ret0, _ := ret[0].([]models.ParkingHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUserParkings indicates an expected call of GetActiveUserParkings.
func (mr *MockParkingHistoryMgrMockRecorder) GetActiveUserParkings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUserParkings", reflect.TypeOf((*MockParkingHistoryMgr)(nil).GetActiveUserParkings), ctx)
}

// GetParkingHistory mocks base method.
func (m *MockParkingHistoryMgr) GetParkingHistory(ctx context.Context, startTime, endTime time.Time) ([]models.ParkingHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParkingHistory", ctx, startTime, endTime)
	ret0, _ := ret[0].([]models.ParkingHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParkingHistory indicates an expected call of GetParkingHistory.
func (mr *MockParkingHistoryMgrMockRecorder) GetParkingHistory(ctx, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParkingHistory", reflect.TypeOf((*MockParkingHistoryMgr)(nil).GetParkingHistory), ctx, startTime, endTime)
}

// GetParkingHistoryByNumberPlate mocks base method.
func (m *MockParkingHistoryMgr) GetParkingHistoryByNumberPlate(ctx context.Context, numberplate string, startTime, endTime time.Time) ([]models.ParkingHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParkingHistoryByNumberPlate", ctx, numberplate, startTime, endTime)
	ret0, _ := ret[0].([]models.ParkingHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParkingHistoryByNumberPlate indicates an expected call of GetParkingHistoryByNumberPlate.
func (mr *MockParkingHistoryMgrMockRecorder) GetParkingHistoryByNumberPlate(ctx, numberplate, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParkingHistoryByNumberPlate", reflect.TypeOf((*MockParkingHistoryMgr)(nil).GetParkingHistoryByNumberPlate), ctx, numberplate, startTime, endTime)
}

// GetParkingHistoryByUserId mocks base method.
func (m *MockParkingHistoryMgr) GetParkingHistoryByUserId(userId string, startTime, endTime time.Time) ([]models.ParkingHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParkingHistoryByUserId", userId, startTime, endTime)
	ret0, _ := ret[0].([]models.ParkingHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParkingHistoryByUserId indicates an expected call of GetParkingHistoryByUserId.
func (mr *MockParkingHistoryMgrMockRecorder) GetParkingHistoryByUserId(userId, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParkingHistoryByUserId", reflect.TypeOf((*MockParkingHistoryMgr)(nil).GetParkingHistoryByUserId), userId, startTime, endTime)
}
