// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/parking_history_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockParkingHistoryStorage is a mock of ParkingHistoryStorage interface.
type MockParkingHistoryStorage struct {
	ctrl     *gomock.Controller
	recorder *MockParkingHistoryStorageMockRecorder
	isgomock struct{}
}

// MockParkingHistoryStorageMockRecorder is the mock recorder for MockParkingHistoryStorage.
type MockParkingHistoryStorageMockRecorder struct {
	mock *MockParkingHistoryStorage
}

// NewMockParkingHistoryStorage creates a new mock instance.
func NewMockParkingHistoryStorage(ctrl *gomock.Controller) *MockParkingHistoryStorage {
	mock := &MockParkingHistoryStorage{ctrl: ctrl}
	mock.recorder = &MockParkingHistoryStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingHistoryStorage) EXPECT() *MockParkingHistoryStorageMockRecorder {
	return m.recorder
}

// AddParking mocks base method.
func (m *MockParkingHistoryStorage) AddParking(vehicle models.Vehicle) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParking", vehicle)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddParking indicates an expected call of AddParking.
func (mr *MockParkingHistoryStorageMockRecorder) AddParking(vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParking", reflect.TypeOf((*MockParkingHistoryStorage)(nil).AddParking), vehicle)
}

// GetActiveUserParkings mocks base method.
func (m *MockParkingHistoryStorage) GetActiveUserParkings(userId string) ([]models.ParkingHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUserParkings", userId)
	ret0, _ := ret[0].([]models.ParkingHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUserParkings indicates an expected call of GetActiveUserParkings.
func (mr *MockParkingHistoryStorageMockRecorder) GetActiveUserParkings(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUserParkings", reflect.TypeOf((*MockParkingHistoryStorage)(nil).GetActiveUserParkings), userId)
}

// GetParkingHistoryByNumberPlate mocks base method.
func (m *MockParkingHistoryStorage) GetParkingHistoryByNumberPlate(numberplate string, startTime, endTime time.Time) ([]models.ParkingHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParkingHistoryByNumberPlate", numberplate, startTime, endTime)
	ret0, _ := ret[0].([]models.ParkingHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParkingHistoryByNumberPlate indicates an expected call of GetParkingHistoryByNumberPlate.
func (mr *MockParkingHistoryStorageMockRecorder) GetParkingHistoryByNumberPlate(numberplate, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParkingHistoryByNumberPlate", reflect.TypeOf((*MockParkingHistoryStorage)(nil).GetParkingHistoryByNumberPlate), numberplate, startTime, endTime)
}

// GetParkingHistoryByUser mocks base method.
func (m *MockParkingHistoryStorage) GetParkingHistoryByUser(userId string, startTime, endTime time.Time) ([]models.ParkingHistoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParkingHistoryByUser", userId, startTime, endTime)
	ret0, _ := ret[0].([]models.ParkingHistoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParkingHistoryByUser indicates an expected call of GetParkingHistoryByUser.
func (mr *MockParkingHistoryStorageMockRecorder) GetParkingHistoryByUser(userId, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParkingHistoryByUser", reflect.TypeOf((*MockParkingHistoryStorage)(nil).GetParkingHistoryByUser), userId, startTime, endTime)
}

// Unpark mocks base method.
func (m *MockParkingHistoryStorage) Unpark(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpark", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unpark indicates an expected call of Unpark.
func (mr *MockParkingHistoryStorageMockRecorder) Unpark(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpark", reflect.TypeOf((*MockParkingHistoryStorage)(nil).Unpark), id)
}

// UnparkByNumberPlate mocks base method.
func (m *MockParkingHistoryStorage) UnparkByNumberPlate(numberplate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnparkByNumberPlate", numberplate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnparkByNumberPlate indicates an expected call of UnparkByNumberPlate.
func (mr *MockParkingHistoryStorageMockRecorder) UnparkByNumberPlate(numberplate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnparkByNumberPlate", reflect.TypeOf((*MockParkingHistoryStorage)(nil).UnparkByNumberPlate), numberplate)
}
