// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/slot_assignment_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSlotAssignmentMgr is a mock of SlotAssignmentMgr interface.
type MockSlotAssignmentMgr struct {
	ctrl     *gomock.Controller
	recorder *MockSlotAssignmentMgrMockRecorder
	isgomock struct{}
}

// MockSlotAssignmentMgrMockRecorder is the mock recorder for MockSlotAssignmentMgr.
type MockSlotAssignmentMgrMockRecorder struct {
	mock *MockSlotAssignmentMgr
}

// NewMockSlotAssignmentMgr creates a new mock instance.
func NewMockSlotAssignmentMgr(ctrl *gomock.Controller) *MockSlotAssignmentMgr {
	mock := &MockSlotAssignmentMgr{ctrl: ctrl}
	mock.recorder = &MockSlotAssignmentMgrMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotAssignmentMgr) EXPECT() *MockSlotAssignmentMgrMockRecorder {
	return m.recorder
}

// AssignSlot mocks base method.
func (m *MockSlotAssignmentMgr) AssignSlot(ctx context.Context, vehicleId string, slot models.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignSlot", ctx, vehicleId, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignSlot indicates an expected call of AssignSlot.
func (mr *MockSlotAssignmentMgrMockRecorder) AssignSlot(ctx, vehicleId, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignSlot", reflect.TypeOf((*MockSlotAssignmentMgr)(nil).AssignSlot), ctx, vehicleId, slot)
}

// AutoAssignSlot mocks base method.
func (m *MockSlotAssignmentMgr) AutoAssignSlot(ctx context.Context, vehicleId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoAssignSlot", ctx, vehicleId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AutoAssignSlot indicates an expected call of AutoAssignSlot.
func (mr *MockSlotAssignmentMgrMockRecorder) AutoAssignSlot(ctx, vehicleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoAssignSlot", reflect.TypeOf((*MockSlotAssignmentMgr)(nil).AutoAssignSlot), ctx, vehicleId)
}
