// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/slot_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	vehicletypes "github.com/Kaushik1766/ParkingManagement/internal/models/enums/vehicle_types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSlotStorage is a mock of SlotStorage interface.
type MockSlotStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSlotStorageMockRecorder
	isgomock struct{}
}

// MockSlotStorageMockRecorder is the mock recorder for MockSlotStorage.
type MockSlotStorageMockRecorder struct {
	mock *MockSlotStorage
}

// NewMockSlotStorage creates a new mock instance.
func NewMockSlotStorage(ctrl *gomock.Controller) *MockSlotStorage {
	mock := &MockSlotStorage{ctrl: ctrl}
	mock.recorder = &MockSlotStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotStorage) EXPECT() *MockSlotStorageMockRecorder {
	return m.recorder
}

// AddSlot mocks base method.
func (m *MockSlotStorage) AddSlot(buildingId uuid.UUID, floorNumber, slotNumber int, slotType vehicletypes.VehicleType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSlot", buildingId, floorNumber, slotNumber, slotType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSlot indicates an expected call of AddSlot.
func (mr *MockSlotStorageMockRecorder) AddSlot(buildingId, floorNumber, slotNumber, slotType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSlot", reflect.TypeOf((*MockSlotStorage)(nil).AddSlot), buildingId, floorNumber, slotNumber, slotType)
}

// DeleteSlot mocks base method.
func (m *MockSlotStorage) DeleteSlot(buildingId uuid.UUID, floorNumber, slotNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSlot", buildingId, floorNumber, slotNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSlot indicates an expected call of DeleteSlot.
func (mr *MockSlotStorageMockRecorder) DeleteSlot(buildingId, floorNumber, slotNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSlot", reflect.TypeOf((*MockSlotStorage)(nil).DeleteSlot), buildingId, floorNumber, slotNumber)
}

// GetFreeSlotsByBuilding mocks base method.
func (m *MockSlotStorage) GetFreeSlotsByBuilding(buildingId uuid.UUID) ([]models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeSlotsByBuilding", buildingId)
	ret0, _ := ret[0].([]models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeSlotsByBuilding indicates an expected call of GetFreeSlotsByBuilding.
func (mr *MockSlotStorageMockRecorder) GetFreeSlotsByBuilding(buildingId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeSlotsByBuilding", reflect.TypeOf((*MockSlotStorage)(nil).GetFreeSlotsByBuilding), buildingId)
}

// GetFreeSlotsByFloor mocks base method.
func (m *MockSlotStorage) GetFreeSlotsByFloor(buildingId uuid.UUID, floorNumber int) ([]models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeSlotsByFloor", buildingId, floorNumber)
	ret0, _ := ret[0].([]models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeSlotsByFloor indicates an expected call of GetFreeSlotsByFloor.
func (mr *MockSlotStorageMockRecorder) GetFreeSlotsByFloor(buildingId, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeSlotsByFloor", reflect.TypeOf((*MockSlotStorage)(nil).GetFreeSlotsByFloor), buildingId, floorNumber)
}

// GetSlotsByFloor mocks base method.
func (m *MockSlotStorage) GetSlotsByFloor(buildingId uuid.UUID, floorNumber int) ([]models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlotsByFloor", buildingId, floorNumber)
	ret0, _ := ret[0].([]models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlotsByFloor indicates an expected call of GetSlotsByFloor.
func (mr *MockSlotStorageMockRecorder) GetSlotsByFloor(buildingId, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlotsByFloor", reflect.TypeOf((*MockSlotStorage)(nil).GetSlotsByFloor), buildingId, floorNumber)
}

// Save mocks base method.
func (m *MockSlotStorage) Save(slot models.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSlotStorageMockRecorder) Save(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSlotStorage)(nil).Save), slot)
}
