// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/slot_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	vehicletypes "github.com/Kaushik1766/ParkingManagement/internal/models/enums/vehicle_types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSlotMgr is a mock of SlotMgr interface.
type MockSlotMgr struct {
	ctrl     *gomock.Controller
	recorder *MockSlotMgrMockRecorder
	isgomock struct{}
}

// MockSlotMgrMockRecorder is the mock recorder for MockSlotMgr.
type MockSlotMgrMockRecorder struct {
	mock *MockSlotMgr
}

// NewMockSlotMgr creates a new mock instance.
func NewMockSlotMgr(ctrl *gomock.Controller) *MockSlotMgr {
	mock := &MockSlotMgr{ctrl: ctrl}
	mock.recorder = &MockSlotMgrMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotMgr) EXPECT() *MockSlotMgrMockRecorder {
	return m.recorder
}

// GetFreeSlotsByBuilding mocks base method.
func (m *MockSlotMgr) GetFreeSlotsByBuilding(ctx context.Context, buildingID uuid.UUID, vehicleType vehicletypes.VehicleType) ([]models.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeSlotsByBuilding", ctx, buildingID, vehicleType)
	ret0, _ := ret[0].([]models.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeSlotsByBuilding indicates an expected call of GetFreeSlotsByBuilding.
func (mr *MockSlotMgrMockRecorder) GetFreeSlotsByBuilding(ctx, buildingID, vehicleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeSlotsByBuilding", reflect.TypeOf((*MockSlotMgr)(nil).GetFreeSlotsByBuilding), ctx, buildingID, vehicleType)
}

// GetSlotsByFloor mocks base method.
func (m *MockSlotMgr) GetSlotsByFloor(ctx context.Context, buildingId string, floorNumber int) ([]models.SlotDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlotsByFloor", ctx, buildingId, floorNumber)
	ret0, _ := ret[0].([]models.SlotDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlotsByFloor indicates an expected call of GetSlotsByFloor.
func (mr *MockSlotMgrMockRecorder) GetSlotsByFloor(ctx, buildingId, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlotsByFloor", reflect.TypeOf((*MockSlotMgr)(nil).GetSlotsByFloor), ctx, buildingId, floorNumber)
}
