// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/user_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	vehicletypes "github.com/Kaushik1766/ParkingManagement/internal/models/enums/vehicle_types"
	gomock "go.uber.org/mock/gomock"
)

// MockUserManager is a mock of UserManager interface.
type MockUserManager struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagerMockRecorder
	isgomock struct{}
}

// MockUserManagerMockRecorder is the mock recorder for MockUserManager.
type MockUserManagerMockRecorder struct {
	mock *MockUserManager
}

// NewMockUserManager creates a new mock instance.
func NewMockUserManager(ctrl *gomock.Controller) *MockUserManager {
	mock := &MockUserManager{ctrl: ctrl}
	mock.recorder = &MockUserManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManager) EXPECT() *MockUserManagerMockRecorder {
	return m.recorder
}

// DeleteProfile mocks base method.
func (m *MockUserManager) DeleteProfile(ctx context.Context, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockUserManagerMockRecorder) DeleteProfile(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockUserManager)(nil).DeleteProfile), ctx, userId)
}

// GetAllUsers mocks base method.
func (m *MockUserManager) GetAllUsers(ctx context.Context) ([]models.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx)
	ret0, _ := ret[0].([]models.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserManagerMockRecorder) GetAllUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserManager)(nil).GetAllUsers), ctx)
}

// GetRegisteredVehicles mocks base method.
func (m *MockUserManager) GetRegisteredVehicles(ctx context.Context) ([]models.VehicleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisteredVehicles", ctx)
	ret0, _ := ret[0].([]models.VehicleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredVehicles indicates an expected call of GetRegisteredVehicles.
func (mr *MockUserManagerMockRecorder) GetRegisteredVehicles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredVehicles", reflect.TypeOf((*MockUserManager)(nil).GetRegisteredVehicles), ctx)
}

// GetUserById mocks base method.
func (m *MockUserManager) GetUserById(ctx context.Context, userId string) (models.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, userId)
	ret0, _ := ret[0].(models.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockUserManagerMockRecorder) GetUserById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockUserManager)(nil).GetUserById), ctx, userId)
}

// GetUserProfile mocks base method.
func (m *MockUserManager) GetUserProfile(ctx context.Context) (models.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx)
	ret0, _ := ret[0].(models.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockUserManagerMockRecorder) GetUserProfile(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockUserManager)(nil).GetUserProfile), ctx)
}

// GetVehiclesByUserId mocks base method.
func (m *MockUserManager) GetVehiclesByUserId(ctx context.Context, userId string) ([]models.VehicleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehiclesByUserId", ctx, userId)
	ret0, _ := ret[0].([]models.VehicleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehiclesByUserId indicates an expected call of GetVehiclesByUserId.
func (mr *MockUserManagerMockRecorder) GetVehiclesByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehiclesByUserId", reflect.TypeOf((*MockUserManager)(nil).GetVehiclesByUserId), ctx, userId)
}

// RegisterVehicle mocks base method.
func (m *MockUserManager) RegisterVehicle(ctx context.Context, numberplate string, vehicleType vehicletypes.VehicleType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterVehicle", ctx, numberplate, vehicleType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterVehicle indicates an expected call of RegisterVehicle.
func (mr *MockUserManagerMockRecorder) RegisterVehicle(ctx, numberplate, vehicleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterVehicle", reflect.TypeOf((*MockUserManager)(nil).RegisterVehicle), ctx, numberplate, vehicleType)
}

// UnregisterVehicle mocks base method.
func (m *MockUserManager) UnregisterVehicle(ctx context.Context, numberplate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterVehicle", ctx, numberplate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterVehicle indicates an expected call of UnregisterVehicle.
func (mr *MockUserManagerMockRecorder) UnregisterVehicle(ctx, numberplate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterVehicle", reflect.TypeOf((*MockUserManager)(nil).UnregisterVehicle), ctx, numberplate)
}

// UpdateProfile mocks base method.
func (m *MockUserManager) UpdateProfile(ctx context.Context, userId string, updateReq models.UpdateUserDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userId, updateReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserManagerMockRecorder) UpdateProfile(ctx, userId, updateReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserManager)(nil).UpdateProfile), ctx, userId, updateReq)
}
