// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../../mocks/vehicle_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Kaushik1766/ParkingManagement/internal/models"
	vehicletypes "github.com/Kaushik1766/ParkingManagement/internal/models/enums/vehicle_types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVehicleStorage is a mock of VehicleStorage interface.
type MockVehicleStorage struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleStorageMockRecorder
	isgomock struct{}
}

// MockVehicleStorageMockRecorder is the mock recorder for MockVehicleStorage.
type MockVehicleStorageMockRecorder struct {
	mock *MockVehicleStorage
}

// NewMockVehicleStorage creates a new mock instance.
func NewMockVehicleStorage(ctrl *gomock.Controller) *MockVehicleStorage {
	mock := &MockVehicleStorage{ctrl: ctrl}
	mock.recorder = &MockVehicleStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleStorage) EXPECT() *MockVehicleStorageMockRecorder {
	return m.recorder
}

// AddVehicle mocks base method.
func (m *MockVehicleStorage) AddVehicle(numberplate string, userid uuid.UUID, vehicleType vehicletypes.VehicleType) (models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVehicle", numberplate, userid, vehicleType)
	ret0, _ := ret[0].(models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddVehicle indicates an expected call of AddVehicle.
func (mr *MockVehicleStorageMockRecorder) AddVehicle(numberplate, userid, vehicleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVehicle", reflect.TypeOf((*MockVehicleStorage)(nil).AddVehicle), numberplate, userid, vehicleType)
}

// GetVehicleById mocks base method.
func (m *MockVehicleStorage) GetVehicleById(vehicleId uuid.UUID) (models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleById", vehicleId)
	ret0, _ := ret[0].(models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleById indicates an expected call of GetVehicleById.
func (mr *MockVehicleStorageMockRecorder) GetVehicleById(vehicleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleById", reflect.TypeOf((*MockVehicleStorage)(nil).GetVehicleById), vehicleId)
}

// GetVehicleByNumberPlate mocks base method.
func (m *MockVehicleStorage) GetVehicleByNumberPlate(numberplate string) (models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByNumberPlate", numberplate)
	ret0, _ := ret[0].(models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleByNumberPlate indicates an expected call of GetVehicleByNumberPlate.
func (mr *MockVehicleStorageMockRecorder) GetVehicleByNumberPlate(numberplate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByNumberPlate", reflect.TypeOf((*MockVehicleStorage)(nil).GetVehicleByNumberPlate), numberplate)
}

// GetVehiclesByUserId mocks base method.
func (m *MockVehicleStorage) GetVehiclesByUserId(userId uuid.UUID) ([]models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehiclesByUserId", userId)
	ret0, _ := ret[0].([]models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehiclesByUserId indicates an expected call of GetVehiclesByUserId.
func (mr *MockVehicleStorageMockRecorder) GetVehiclesByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehiclesByUserId", reflect.TypeOf((*MockVehicleStorage)(nil).GetVehiclesByUserId), userId)
}

// GetVehiclesWithUnassignedSlots mocks base method.
func (m *MockVehicleStorage) GetVehiclesWithUnassignedSlots() ([]models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehiclesWithUnassignedSlots")
	ret0, _ := ret[0].([]models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehiclesWithUnassignedSlots indicates an expected call of GetVehiclesWithUnassignedSlots.
func (mr *MockVehicleStorageMockRecorder) GetVehiclesWithUnassignedSlots() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehiclesWithUnassignedSlots", reflect.TypeOf((*MockVehicleStorage)(nil).GetVehiclesWithUnassignedSlots))
}

// RemoveVehicle mocks base method.
func (m *MockVehicleStorage) RemoveVehicle(numberplate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVehicle", numberplate)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveVehicle indicates an expected call of RemoveVehicle.
func (mr *MockVehicleStorageMockRecorder) RemoveVehicle(numberplate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVehicle", reflect.TypeOf((*MockVehicleStorage)(nil).RemoveVehicle), numberplate)
}

// Save mocks base method.
func (m *MockVehicleStorage) Save(vehicle models.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", vehicle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockVehicleStorageMockRecorder) Save(vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockVehicleStorage)(nil).Save), vehicle)
}
