// Code generated by "stringer -type=VehicleType"; DO NOT EDIT.

package vehicletypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TwoWheeler-0]
	_ = x[FourWheeler-1]
}

const _VehicleType_name = "TwoWheelerFourWheeler"

var _VehicleType_index = [...]uint8{0, 10, 21}

func (i VehicleType) String() string {
	if i < 0 || i >= VehicleType(len(_VehicleType_index)-1) {
		return "VehicleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VehicleType_name[_VehicleType_index[i]:_VehicleType_index[i+1]]
}
